/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.fsm.service;
import cn.zhuatech.fsm.common.BusinessException; import cn.zhuatech.fsm.dto.FsmDto.*; import cn.zhuatech.fsm.model.*; import cn.zhuatech.fsm.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class FsmService {
    private final WorkOrderRepository orders; private final ServiceReportRepository reports; private final TechnicianRepository technician; private final SafetyInspectionRepository safetyInspections; private final CurrentUserService current;
    public FsmService(WorkOrderRepository orders,ServiceReportRepository reports,TechnicianRepository technician,SafetyInspectionRepository safetyInspections,CurrentUserService current){this.orders=orders;this.reports=reports;this.technician=technician;this.safetyInspections=safetyInspections;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getServiceRegionCode();List<WorkOrder> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByServiceRegionCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<WorkOrderView> workOrders(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){WorkOrder order=orders.findById(id).orElseThrow(()->new BusinessException("现场服务任务不存在"));if(order.getStatus()==WorkOrder.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new ServiceReport(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<WorkOrder> list){int planned=list.stream().mapToInt(WorkOrder::getPlannedQty).sum(),done=list.stream().mapToInt(WorkOrder::getCompletedQty).sum(),defects=list.stream().mapToInt(WorkOrder::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日现场服务",String.format("%,d",planned),list.size()+" 张现场服务任务","blue"),new Metric("现场服务完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("工程师异常",technician.countByStatus(Technician.Status.ALARM)+"",safetyInspections.countByResult(SafetyInspection.Result.PENDING)+" 项待验收","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),technician.findAllByOrderByCodeAsc().stream().map(e->new TechnicianView(e.getCode(),e.getName(),e.getServiceRegion().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),safetyInspections.findTop10ByOrderByIdDesc().stream().map(i->new SafetyInspectionView(i.getSafetyInspectionNo(),i.getWorkOrder().getOrderNo(),i.getWorkOrder().getProductName(),i.getSafetyInspectionType(),i.getSafetyInspectionQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private WorkOrderView view(WorkOrder o){return new WorkOrderView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getServiceRegion().getName(),o.getServiceRegion().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(WorkOrder o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
